wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1698104259
    t:
      1:
      - 1
      - 41
      - 55
      - 63
      3:
      - 1
      - 16
      4: 3.8.5
      5: 0.12.21
      8:
      - 8
accum_iter:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 16
bold5000_path:
  desc: null
  value: ./data/BOLD5000
bold5000_subs:
  desc: null
  value:
  - CSI1
clip_grad:
  desc: null
  value: 0.8
dataset:
  desc: null
  value: GOD
include_nonavg_test:
  desc: null
  value: true
kam_path:
  desc: null
  value: ./data/Kamitani/npz
kam_subs:
  desc: null
  value:
  - sbj_3
local_rank:
  desc: null
  value: 0
lr:
  desc: null
  value: 5.3e-05
mask_ratio:
  desc: null
  value: 0.75
min_lr:
  desc: null
  value: 0.0
num_epoch:
  desc: null
  value: 15
output_path:
  desc: null
  value: ./results/fmri_finetune/23-10-2023-16-37-39
pretrain_mbm_path:
  desc: null
  value: ./pretrains/GOD/fmri_encoder.pth
root_path:
  desc: null
  value: .
warmup_epochs:
  desc: null
  value: 2
weight_decay:
  desc: null
  value: 0.05
